"""add duplicate report path to institution

Revision ID: 94dc7eacea27
Revises: ac51092a3d72
Create Date: 2025-08-26 16:39:42.592998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94dc7eacea27'
down_revision: Union[str, Sequence[str], None] = 'ac51092a3d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('duplicate_report_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'duplicate_report_path')
    # ### end Alembic commands ###
