#file: noinspection UndefinedParamsPresent,UndefinedAction
name: Update Poetry Dependencies

on:
  schedule:
    - cron: '0 11 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  get-terraform-outputs:
    name: Get Terraform outputs
    runs-on: ubuntu-latest
    outputs:
      python_version: ${{ steps.get_outputs.outputs.python_version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.TF_STATE_RG }}" \
            -backend-config="storage_account_name=${{ secrets.TF_STATE_SA }}" \
            -backend-config="container_name=${{ secrets.TF_STATE_CONTAINER }}" \
            -backend-config="key=${{ secrets.TF_STATE_KEY }}"

      - name: Get Terraform Outputs
        id: get_outputs
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          PYTHON_VERSION=$(terraform output -raw python_version)
          echo "python_version=$PYTHON_VERSION" >> "$GITHUB_OUTPUT"

  update-dependencies:
    name: Update dependencies
    runs-on: ubuntu-latest
    needs: get-terraform-outputs

    env:
      PYTHON_VERSION: ${{ needs.get-terraform-outputs.outputs.python_version }}

    steps:
      - uses: webfactory/ssh-agent@v0.9
        with:
          ssh-private-key: ${{ secrets.AZURE_DEVOPS_SSH_KEY }}

      - uses: fuzzylabs/gha-poetry-update@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: 'latest'
