#file: noinspection UndefinedParamsPresent,UndefinedAction
name: Update Poetry Dependencies

on:
  schedule:
    - cron: '0 11 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update Poetry Dependencies
      uses: fuzzylabs/gha-poetry-update@v2
      with:
        python-version: '3.12'
        poetry-version: 'latest'
        branch-name: 'dependency-updates-${{ github.run_number }}-${{ github.run_attempt }}'
        pr-title: 'chore: update poetry dependencies'
        commit-message: 'chore: update poetry dependencies. Automated dependency update performed on ${{ github.run_id }}'
        fail-on-no-updates: false
        pr-labels: |
          dependencies
          automated
          python
